#!/bin/sh
# check - runs shellcheck on the shell scripts in this project
#
# This file is part of jacques-clouseau, various keen and handy inspectors.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

looks_like_shell_script() {
    head -n 1 -- "$f" | grep -qE '^#!.*sh(?:[[:blank:]]|$)'
}

for f in *; do
    if [ -f "$f" ] && [ -x "$f" ] && looks_like_shell_script "$f"; then
        printf 'Checking %s for errors.\n' "$f"
        shellcheck -- "$f"
    fi
done
