#!/usr/bin/env bash
# penv - prints environment variables case-insensitively

# This file is part of jacques-clouseau, various keen and handy inspectors.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

set -efo pipefail

declare -Ai keys
for key in "${@,,}"; do keys["$key"]=1; done
readonly -A keys

printenv | while IFS='=' read -r name value; do
    if [ -v "keys[${name,,}]" ]; then
        printf '%s=%s\n' "$name" "$value"
    fi
done
