#!/usr/bin/env bash
# that - like which, but explicitly traverses symlinks

follow() {
    local path
    path="$(type -P "$1")" || return

    while true; do
        printf '%s\n' "$path"
        path="$(readlink "$path")" || break
    done
}

sep=
for arg; do
    printf '%s' "$sep"; sep=$'\n'
    follow "$arg"
done
