#!/usr/bin/env bash
# that - like which, but explicitly traverses symlinks
#
# This file is part of jacques-clouseau, various keen and handy inspectors.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

follow() {
    local path
    path="$(type -P -- "$1")" || return

    while true; do
        printf '%s\n' "$path"
        path="$(readlink -- "$path")" || break
    done
}

sep=
for arg; do
    printf '%s' "$sep"; sep=$'\n'
    follow "$arg"
done
